/** Funny sample tasks cycled as quick-add placeholder text. ~200 of them. */
export const SAMPLE_TASKS: string[] = [
  "Water the plant before it files a complaint",
  "Reply to that email from three weeks ago tomorrow",
  "Pretend to understand the standup #work",
  "Find out what the red light on the dishwasher means",
  "Cancel the subscription I forgot I had",
  "Stop opening 47 browser tabs !!",
  "Buy milk before the cereal stages a protest",
  "Schedule a meeting to plan the other meeting #work",
  "Learn to fold a fitted sheet (lifelong project) 🔁 every year",
  "Update the thing before the other thing breaks",
  "Drink water like a functional adult 🔁 every day",
  "Back up the backups #engineering",
  "Reboot the router with great ceremony",
  "Find the charger that vanished into the void",
  "Apologize to the calendar for ignoring it",
  "Read one page of that book by Friday",
  "Delete 10,000 photos of the same sunset",
  "Renew the domain before it's squatted",
  "Pay the invoice before it pays a visit #work",
  "Touch grass, allegedly",
  "Migrate the database and pray #engineering tomorrow",
  "Name the houseplant something dignified",
  "Stretch so the chair stops winning",
  "Reply 'sounds good' to seventeen threads",
  "Find a pen that actually works",
  "Defrag my life next monday",
  "Email Dana about the Q3 numbers tomorrow #work",
  "Stop saying 'circle back' #work",
  "Test the fire alarm, briefly 🔁 every month",
  "Learn the new framework that replaced the last one #engineering",
  "Floss, theoretically 🔁 every day",
  "Find the source of the mystery beep",
  "Approve the PR before it gets feelings #engineering",
  "Buy a plant I will definitely keep alive",
  "Schedule the dentist I keep ghosting",
  "Take out the recycling before it achieves sentience 🔁 every week",
  "Reply to mom before she calls the police",
  "Update LinkedIn so recruiters stop guessing",
  "Finish the side project (it's been 'almost done' since 2021)",
  "Charge every device simultaneously, impossibly",
  "Find out who keeps booking the conference room #work",
  "Write the README nobody will read #engineering",
  "Unsubscribe from the newsletter I never read 🔁 every week",
  "Wash the one mug I actually use",
  "Pretend the inbox is at zero",
  "Buy a birthday gift, ideally on time",
  "Restart the laptop it's been 92 days",
  "Move the car before street cleaning ⏰ 08:00",
  "Plan the trip I keep talking about",
  "Return the library book from the Obama era",
  "Set a password that isn't the old one + 1",
  "Decline the meeting that could've been an email #work",
  "Hydrate the sourdough starter or let it pass 🔁 every day",
  "Find my other sock (cold case)",
  "Confirm the thing is plugged in #engineering",
  "Buy groceries before becoming a feral raccoon",
  "Reply to the group chat from yesterday",
  "Schedule a haircut before I'm mistaken for a yeti",
  "Update the dependencies, then fix everything #engineering",
  "Take a walk that isn't to the fridge",
  "Clear the downloads folder of 600 screenshots",
  "Find a parking spot in this dimension",
  "Make the bed (radical self-care) 🔁 every day",
  "Call the bank and wait on hold forever",
  "Write down the idea before it evaporates",
  "Empty the dishwasher I keep relabeling 'still dirty'",
  "Book a vacation, then a vacation from planning it",
  "Stop the gym membership from haunting me",
  "Reply to the recruiter with a polite no",
  "Charge the AirPod that's always dead",
  "Plan dinner before 5pm panic sets in 🔁 every day",
  "Refill the printer with the mythical ink",
  "Fix the wobbly table with folded cardboard, permanently",
  "Read the terms and conditions (just kidding)",
  "Renew car insurance before it lapses",
  "Learn to say no to one (1) thing",
  "Archive Slack before it archives me #work",
  "Take vitamins I bought to feel responsible 🔁 every day",
  "Find the warranty I definitely saved somewhere",
  "Schedule the oil change overdue by 3,000 miles",
  "Reply to the wedding RSVP",
  "Clean the keyboard of ancient crumbs",
  "Update the resume just in case #work",
  "Water the office plant nobody adopted 🔁 every week",
  "Defeat the one notification badge that won't die",
  "Buy a gift card as a last-minute hero",
  "Find the TV remote (suspect the couch)",
  "Write the standup update before standup #work",
  "Deploy on a Friday, live dangerously #engineering",
  "Call grandma, she has stories",
  "Sort the junk drawer of forbidden cables",
  "Set out clothes so mornings aren't chaos",
  "Reply to the calendar invite with maybe",
  "Cancel the free trial before it bites",
  "Mute the group chat lovingly",
  "Find the receipt for the return window closing today",
  "Buy stamps like it's 1998",
  "Restart the wifi with hope in my heart",
  "Take the trash out before it's archaeology 🔁 every week",
  "Update macOS during a meeting (bold)",
  "Plan the offsite nobody asked for #work",
  "Refactor the function I'm scared of #engineering",
  "Schedule a check-up I keep postponing",
  "Buy a charger cable that survives a week",
  "Reply to the text I left on read",
  "Find motivation (last seen Tuesday)",
  "Clean the camera lens before the call #work",
  "Pay the parking ticket before it multiplies",
  "Label the leftovers before they become science",
  "Practice the elevator pitch in the elevator",
  "Order the part to fix the thing to fix the other thing",
  "Charge the e-bike before tomorrow's ride",
  "Find a dog-sitter for the weekend",
  "Cancel the meeting I scheduled in a panic #work",
  "Replace the toothbrush from a previous era",
  "Submit the expense report before accounting hunts me #work",
  "Take the dog out before negotiations fail 🔁 every day",
  "Update the spreadsheet of doom #work",
  "Buy a houseplant that thrives on neglect",
  "Reply 'let's grab coffee' and never schedule it",
  "Find the missing semicolon #engineering",
  "Clear browser tabs before the laptop sighs",
  "Schedule 1:1 with the manager #work",
  "Order more coffee before withdrawal 🔁 every week",
  "Test in production, apologize later #engineering",
  "Sign the form that's been on the fridge for a month",
  "Set up the new monitor still in its box",
  "Reply to the survey for the $5 gift card",
  "Find my keys (they're in the other pocket)",
  "Vacuum before the dust bunnies unionize 🔁 every week",
  "Update the firmware that bricks everything",
  "Call the plumber about the suspicious drip",
  "Write thank-you notes from last month",
  "Cancel the meeting series nobody attends #work",
  "Buy batteries for the smoke detector chirp",
  "Plan a budget I'll ignore by Tuesday 🔁 every month",
  "Reply to the landlord about the heating",
  "Charge the camera before the trip",
  "Find the perfect gif for the channel #work",
  "Roll the recycling bin out 🔁 every week ⏰ 07:30",
  "Read the doc before the meeting (revolutionary) #work",
  "Schedule a massage I'll cancel anyway",
  "Update the password manager master password",
  "Buy a new whisk; the old one whisks no more",
  "Reply to the comment from code review #engineering",
  "Set the thermostat to a number we both hate",
  "Order the cake before the party tomorrow",
  "Clean out the email folder named 'misc (2,431)'",
  "Find the AUX cable from the before times",
  "Schedule the car for its 'check engine' mystery",
  "Reply to the Slack thread from this morning #work",
  "Renew the gym membership to feel virtuous",
  "Buy a plant pot for the plant in the cup",
  "Take a screenshot for the bug report #engineering",
  "Refill the soap before guilt sets in",
  "Plan the grocery list, then forget it at home",
  "Cancel the calendar reminder that mocks me daily",
  "Find the lid that fits this container",
  "Write the blog post draft I keep avoiding",
  "Schedule the haircut before the wedding",
  "Update the team on the thing #work",
  "Buy a doormat that says something passive-aggressive",
  "Restart the build, again #engineering",
  "Reply to the email with one word: 'thanks'",
  "Charge the power bank that's always empty",
  "Plan the week on Sunday like an optimist 🔁 every week",
  "Take the laundry out before it wrinkles into origami",
  "Find the missing AirTag (the irony)",
  "Schedule the vet appointment for the goblin cat",
  "Submit the timesheet before payroll cries #work",
  "Buy a new sponge; this one has opinions",
  "Reply to the meeting notes with 'lgtm' #work",
  "Order printer ink at scandalous prices",
  "Update the wiki nobody reads #engineering",
  "Set an alarm I'll snooze nine times",
  "Find the warranty card for the toaster",
  "Plan a date night that isn't ordering pizza",
  "Cancel the trial before the silent charge",
  "Reply to the customer before they tweet #work",
  "Buy a plant light for the sad fern",
  "Clear the desktop of 200 untitled files",
  "Schedule the inspection before the deadline",
  "Take a break before the keyboard fuses to my hands",
  "Update the changelog #engineering",
  "Find the second earbud (it's always the left)",
  "Reply to the invite I've dodged twice",
  "Buy a phone case before the next drop",
  "Restart standup energy with caffeine #work",
  "Order the thing before free shipping ends",
  "Plan retirement, eventually, somehow",
  "Take out the compost before it ferments 🔁 every week",
  "Reply to the form before it closes at midnight ⏰ 23:00",
  "Find a babysitter for Saturday",
  "Update the budget after the splurge #money",
  "Schedule the follow-up nobody wants #work",
  "Buy a notebook to write down which notebook things go in",
];
